"""The craft properties that separate placed pixel art from a rendered picture.

`quality` measures whether a drawing has form, `ramplint` measures whether its colour is
coherent, and `figure` measures whether its shapes hold together. None of them measures
whether the thing was *made as pixel art*, and that turned out to be the difference
between this project's output and the reference work it was being compared against.

Measured on four reference pieces supplied as a quality bar, three of them were not pixel
art at all: 85 to 96 percent of their colour clusters were single pixels and they carried
3,000 to 145,000 colours, because they are illustrations put through a pixel-style filter.
The fourth sat on a 4px grid and still ran 96 percent singletons. Chasing that density in
indexed art produces noise, and nothing in this module's siblings could say so.

So this module answers four questions that the others cannot:

* **Is the colour placed or painted?** `clusters` reports the size distribution of
  single-colour regions. Placed pixel art builds areas; a filtered photograph builds
  speckle.
* **Is the silhouette drawn or ruled?** `edge_runs` reports the run lengths down the
  drawing's outer edges. A drawn curve varies them; a shape generated by interpolating
  between two endpoints repeats one.
* **Does the picture have a value structure?** `value_split` reports how luminance
  distributes. A figure on transparency has no structure at all, which is why it reads as
  an asset rather than as a picture.
* **Is the darkest thing the keyline?** `keyline_integrity` answers it, because three
  separate ramps in one session bottomed out at pure black and silently beat the outline
  they were drawn beside.

Every function here measures and reports. Thresholds live in `readings`, are stated with
their provenance, and are kept deliberately few: the corpus that would earn more of them
does not exist yet, and a threshold without one is an opinion wearing a number.
"""

from __future__ import annotations

from .quality import Grid, _rgba, bounding_box, luminance

# ============================================================================ DISCARDED
# Three thresholds were written for this module and all three were discarded the same
# afternoon, by the gate in `validation.discordant_pairs`: any pair where known-good art
# scores worse than known-bad discards the measure rather than retuning it, because no
# choice of threshold repairs an ordering. Measured over `tests/corpus`:
#
#     singleton_share   AUC 0.619   132 discordant pairs
#     share_in_8plus    AUC 0.674   116 discordant pairs
#     edge_variety      AUC 0.168   277 discordant pairs
#
# The reason generalises and is worth keeping. Good art in this corpus runs 0% to 68%
# singletons and bad art 36% to 47%, so the ranges overlap almost completely and the good
# side is the wider one: a clean item sheet with deliberate single-pixel detail scores
# "worse" than a muddy figure. Edge variety inverts outright, 0.168, because a sprite
# sheet's panels have perfectly straight edges (variety 1) and are perfectly good art,
# while the known-bad golem has the most varied edges in the set at 8.
#
# A fourth, "the darkest colour should lie against the silhouette border", fired on 5 of
# 12 good samples and was dropped with them.
#
# What this means in practice: these numbers describe a drawing, they do not judge one.
# They are reported by `score` and read by a person. The one check here that does judge is
# `ramp_floor_clears`, and it survives for the same reason `palette_conformance` does: it
# is definitional rather than aesthetic. A ramp step is darker than the keyline or it is
# not, and that does not vary with the subject.


def _cells(grid: Grid) -> dict[tuple[int, int], str]:
    out = {}
    for y, row in enumerate(grid):
        for x, color in enumerate(row):
            if _rgba(color)[3] > 0:
                out[(x, y)] = color
    return out


def clusters(grid: Grid) -> dict:
    """The size distribution of 4-connected single-colour regions.

    This is the first principle of the craft and the one measurement that separates art
    whose colour was *placed* from art whose colour was *computed*. A region here is a
    run of touching pixels sharing one exact colour: a lit pauldron face, a band of sky,
    the flat of a blade.

    Four-connected rather than eight on purpose. Two areas meeting only at their corners
    are two areas to the eye as well, and counting them as one would report a drawing as
    tidier than it looks.

    `share_in_8plus` is the useful number. Singleton share alone punishes legitimate
    anti-aliasing and deliberate single-pixel detail, while the share of *pixels* living
    in substantial regions says whether the drawing is built from areas at all.
    """
    cells = _cells(grid)
    seen: set[tuple[int, int]] = set()
    sizes: list[int] = []
    for key in cells:
        if key in seen:
            continue
        colour = cells[key]
        stack, size = [key], 0
        seen.add(key)
        while stack:
            x, y = stack.pop()
            size += 1
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                near = (x + dx, y + dy)
                if near in cells and near not in seen and cells[near] == colour:
                    seen.add(near)
                    stack.append(near)
        sizes.append(size)
    if not sizes:
        return {"regions": 0, "drawn": 0, "median": 0, "largest": 0,
                "singleton_share": 0.0, "share_in_8plus": 0.0}
    sizes.sort()
    drawn = sum(sizes)
    return {
        "regions": len(sizes),
        "drawn": drawn,
        "median": sizes[len(sizes) // 2],
        "largest": sizes[-1],
        "singleton_share": round(sum(1 for s in sizes if s == 1) / len(sizes), 3),
        "share_in_8plus": round(sum(s for s in sizes if s >= 8) / drawn, 3),
    }


def edge_runs(grid: Grid) -> dict:
    """Run lengths down the drawing's leftmost and rightmost edges.

    A silhouette is a sequence of run lengths and the sequence *is* the drawing. A curve
    placed by hand varies it (4, 3, 2, 1, 1, 2); a curve produced by interpolating between
    two endpoints repeats one value, which reads as a ruled line however the shape is
    shaded afterwards.

    `distinct` and not the longest repeated stretch, which was the first version of this
    and was wrong: a clean 45 degree edge is every run length 1 and a 2:1 edge is every
    run length 2, so both scored as maximally banded while being ordinary pixel art. The
    fault worth reporting is an edge built from one run length and nothing else.
    """
    cells = _cells(grid)
    if not cells:
        return {"distinct": 0, "runs": [], "longest_repeat": 0}
    per_row: dict[int, tuple[int, int]] = {}
    for x, y in cells:
        low, high = per_row.get(y, (x, x))
        per_row[y] = (min(low, x), max(high, x))
    runs: list[int] = []
    for side in (0, 1):
        edge = [per_row[y][side] for y in sorted(per_row)]
        current = 1
        for i in range(1, len(edge)):
            if edge[i] == edge[i - 1]:
                current += 1
            else:
                runs.append(current)
                current = 1
        runs.append(current)
    longest, streak = 1, 1
    for i in range(1, len(runs)):
        streak = streak + 1 if runs[i] == runs[i - 1] else 1
        longest = max(longest, streak)
    return {"distinct": len(set(runs)), "runs": runs, "longest_repeat": longest}


def value_split(grid: Grid, dark: float = 0.06, light: float = 0.30) -> dict:
    """How the drawing's luminance distributes across dark, middle and light.

    A picture has a value structure and an asset on transparency does not, which is the
    difference this measures. Reference illustrations supplied as a quality bar split
    39/15/45 and 45/49/6 across these three bands; a figure drawn on nothing sits at
    100/0/0 and has no ground to be read against at all.

    The band edges are luminances rather than shares, so the answer does not change with
    how much of the canvas happens to be drawn.
    """
    values = [luminance(_rgba(c)) for row in grid for c in row if _rgba(c)[3] > 0]
    if not values:
        return {"dark": 0.0, "mid": 0.0, "light": 0.0, "median": 0.0, "bimodal": False}
    values.sort()
    low = sum(1 for v in values if v < dark)
    high = sum(1 for v in values if v >= light)
    total = len(values)
    mid = total - low - high
    return {
        "dark": round(low / total, 3),
        "mid": round(mid / total, 3),
        "light": round(high / total, 3),
        "median": round(values[total // 2], 4),
        # The references that read strongest put most of their pixels at the two ends and
        # little between, so the figure separates from the ground by value alone.
        "bimodal": (low + high) / total > 0.75 and mid / total < 0.25,
    }


def keyline_integrity(grid: Grid, keyline: str | None = None) -> dict:
    """Whether the darkest colour in the drawing is the one bounding it.

    Written because the same fault appeared three times in one session from three
    different ramps: a generated ramp whose darkest step lands on or near pure black is
    darker than any sensible outline, so the drawing's darkest colour becomes a handful
    of interior shadow pixels and the keyline stops being measurable at all. Nothing
    caught it, including `ramp_chroma`, because a step at pure black has no hue and so is
    not a grey step.

    Pass `keyline` to check a specific intended colour; omit it to be told what the
    darkest colour actually is and how much of the drawing sits on it.
    """
    cells = _cells(grid)
    if not cells:
        return {"darkest": None, "share": 0.0, "bounds": False, "matches": None}
    counts: dict[str, int] = {}
    for colour in cells.values():
        counts[colour] = counts.get(colour, 0) + 1
    darkest = min(counts, key=lambda c: luminance(_rgba(c)))
    box = bounding_box(grid)
    on_edge = 0
    if box is not None:
        for (x, y), colour in cells.items():
            if colour != darkest:
                continue
            if any((x + dx, y + dy) not in cells
                   for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))):
                on_edge += 1
    total_darkest = counts[darkest]
    out = {
        "darkest": darkest,
        "share": round(total_darkest / len(cells), 3),
        # A keyline lies against the silhouette's border. A dark colour that mostly does
        # not is an interior shadow wearing the keyline's crown.
        "bounds": total_darkest > 0 and on_edge / total_darkest > 0.5,
        "matches": None,
    }
    if keyline is not None:
        out["matches"] = darkest.lower()[:7] == keyline.lower()[:7]
    return out


def ramp_floor_clears(ramp: list[str], keyline: str) -> bool:
    """Is every step of a ramp lighter than the keyline it will be drawn beside.

    The guard for the fault above, meant to be called where ramps are chosen rather than
    after a sprite is built. Three ramps in one piece failed it.
    """
    floor = luminance(_rgba(keyline))
    return all(luminance(_rgba(step)) > floor for step in ramp)


def readings(metrics: dict) -> list[str]:
    """What the craft measurements are worth saying out loud, which is nothing.

    Every threshold proposed for this module failed the ranking gate on the labelled
    corpus; see the DISCARDED block at the top of the file for the numbers and the reason.
    The function exists so callers have the same shape here as in `quality` and
    `ramplint`, and so that a future measure which *does* earn a threshold has somewhere
    to go. Returning an empty list is the honest answer, not an unfinished one.
    """
    return []


def score(grid: Grid, keyline: str | None = None) -> dict:
    """Every craft measurement at once."""
    return {
        "clusters": clusters(grid),
        "edge_runs": edge_runs(grid),
        "value_split": value_split(grid),
        "keyline": keyline_integrity(grid, keyline),
    }
