"""Minecraft resource-pack tools — put a texture where the game will actually find it.

Four tools over the domain logic in ``core/minecraft.py``:

  * ``write_pack_mcmeta`` — make a directory a loadable resource pack.
  * ``export_minecraft_texture`` — export a sprite to
    ``<pack>/assets/<ns>/textures/<category>/<name>.png``, as a vertical frame strip plus
    a ``.png.mcmeta`` sidecar when the sprite is animated.
  * ``write_texture_mcmeta`` — write or repair that sidecar on its own.
  * ``validate_minecraft_texture`` — check size, power-of-two, frame count, sidecar
    presence and tiling seams before the pack ships.

Every failure these catch is one the game reports badly or not at all: a missing sidecar
shows as squashed art, a non-power-of-two size as broken mipmaps, a tiling seam as a grid
of lines across a wall that looked fine in the editor.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..app import mcp
from ..core import minecraft as mc
from ..core.errors import ExportError
from ..core.manifest import file_entry, sprite_summary, workflow_manifest
from ..core.paths import ensure_output_path
from . import export, inspect

# get_pixels caps a single read at 4096 pixels, so wide textures are read in horizontal
# bands and stitched. Reading only the edges would be cheaper but would leave nothing to
# compare a wrap transition against — the seam check is a comparison, not a measurement.
_PIXELS_PER_READ = 4096


# --------------------------------------------------------------------------- #
# Pack scaffolding                                                            #
# --------------------------------------------------------------------------- #
@mcp.tool()
def write_pack_mcmeta(
    pack_root: str,
    mc_version: str | None = None,
    pack_format: int | None = None,
    description: str = "Generated by aseprite-mcp",
    supported_min: int | None = None,
    supported_max: int | None = None,
    overwrite: bool = False,
) -> dict:
    """Write ``<pack_root>/pack.mcmeta`` — the file that makes a directory a resource pack.

    Args:
        pack_root: Directory to become the pack root (created if needed).
        mc_version: A known Minecraft version (e.g. "1.21.1") to look the format up from.
            Defaults to 1.21.1.
        pack_format: The format number, overriding `mc_version`. Required for versions
            outside the known table — an unverified guess produces a pack the game
            rejects as incompatible, so it is refused rather than guessed.
        supported_min, supported_max: Optional inclusive `supported_formats` range,
            letting one pack load across several game versions.

    Returns a ``workflow_manifest.v1`` manifest (kind ``minecraft_pack``).
    """
    resolved_format = mc.resolve_pack_format(mc_version, pack_format)
    supported = None
    if supported_min is not None or supported_max is not None:
        if supported_min is None or supported_max is None:
            raise ExportError("supported_min and supported_max must be given together.")
        if supported_min > supported_max:
            raise ExportError(
                f"supported_min ({supported_min}) is greater than supported_max "
                f"({supported_max})."
            )
        supported = {"min_inclusive": supported_min, "max_inclusive": supported_max}

    document = mc.pack_mcmeta(resolved_format, description, supported)
    out = ensure_output_path(f"{pack_root}/pack.mcmeta", overwrite=overwrite,
                             error_type=ExportError)
    out.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8", newline="\n")

    return workflow_manifest(
        "minecraft_pack",
        created_files=[file_entry("metadata", str(out), "mcmeta")],
        suggested_next_actions=[
            f"pack.mcmeta written with pack_format {resolved_format}"
            + (f" (from Minecraft {mc_version or mc.DEFAULT_MC_VERSION})"
               if pack_format is None else " (explicit)"),
            "Add textures with export_minecraft_texture(..., pack_root=...).",
            f"Drop '{pack_root}' into .minecraft/resourcepacks/ to test it in game.",
        ],
    )


@mcp.tool()
def write_texture_mcmeta(
    texture_path: str,
    frametime: int = 1,
    interpolate: bool = False,
    frame_order: list | None = None,
    frame_width: int | None = None,
    frame_height: int | None = None,
    overwrite: bool = False,
) -> dict:
    """Write the ``<texture>.png.mcmeta`` sidecar for an animated texture.

    ``export_minecraft_texture`` writes this automatically for a multi-frame sprite; use
    this to add or repair one beside a PNG that already exists.

    Args:
        texture_path: Path to the ``.png`` (the sidecar goes beside it, same name + .mcmeta).
        frametime: Ticks each frame is shown for (1 tick = 50 ms).
        interpolate: Blend between frames — smooth for gradients, blurry for pixel art.
        frame_order: Optional playback order: frame indices (0-based) or
            ``{"index": i, "time": t}`` objects to hold individual frames longer.
        frame_width, frame_height: Only for non-square frames, which the game otherwise
            infers from the strip's width.

    Returns a ``workflow_manifest.v1`` manifest (kind ``minecraft_texture``).
    """
    if not str(texture_path).endswith(".png"):
        raise ExportError(
            f"texture_path should be the .png itself (got {texture_path!r}); the sidecar is "
            "named <texture>.png.mcmeta."
        )
    document = mc.animation_mcmeta(frametime, interpolate, frame_order,
                                   frame_width, frame_height)
    out = ensure_output_path(f"{texture_path}.mcmeta", overwrite=overwrite,
                             error_type=ExportError)
    out.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8", newline="\n")
    return workflow_manifest(
        "minecraft_texture",
        created_files=[file_entry("metadata", str(out), "mcmeta")],
        suggested_next_actions=[
            (f"Sidecar written: {out.name}. The PNG must be a vertical strip of square "
             "frames for it to mean anything."),
        ],
    )


# --------------------------------------------------------------------------- #
# Export                                                                      #
# --------------------------------------------------------------------------- #
@mcp.tool()
def export_minecraft_texture(
    filename: str,
    pack_root: str,
    namespace: str = "minecraft",
    category: str = "block",
    texture_name: str | None = None,
    frametime: int = 1,
    interpolate: bool = False,
    frame_order: list | None = None,
    overwrite: bool = False,
) -> dict:
    """Export a sprite into a resource pack at its correct texture path.

    A single-frame sprite exports as a plain PNG. A multi-frame sprite exports as a
    **vertical strip** (frame 1 on top, no padding) and gets a ``.png.mcmeta`` sidecar —
    that pairing is what the game reads as an animation, and either half alone is broken.

    Args:
        pack_root: The resource-pack directory (its ``assets/`` tree is written under this).
        namespace: Your mod/pack id. Defaults to "minecraft", which overrides vanilla.
        category: Texture subdirectory — block, item, entity, gui, particle, ...
        texture_name: In-pack texture name, ``/`` allowed for subdirectories. Defaults to
            the sprite's filename stem.
        frametime: Ticks per frame for the animation sidecar (1 tick = 50 ms).
        interpolate: Blend between animation frames.
        frame_order: Optional playback order (see ``write_texture_mcmeta``).
        overwrite: Replace existing files (default False = no-clobber).

    Returns a ``workflow_manifest.v1`` manifest (kind ``minecraft_texture``).
    """
    if namespace and not mc.NAMESPACE_RE.match(namespace):
        raise ExportError(
            f"namespace {namespace!r} must match [a-z0-9_.-]+ — resource locations are "
            "lowercase, and an uppercase pack loads from a folder but 404s from a zip."
        )
    if category not in mc.TEXTURE_CATEGORIES:
        raise ExportError(
            f"category {category!r} is not a texture directory; expected one of "
            f"{list(mc.TEXTURE_CATEGORIES)}."
        )
    name = texture_name or Path(filename).stem
    if not mc.TEXTURE_NAME_RE.match(name):
        raise ExportError(
            f"texture name {name!r} is not a valid resource path — lowercase [a-z0-9_.-] "
            "with '/' as the only separator."
        )

    info = inspect.get_sprite_info(filename)
    frames = info["frameCount"]
    rel = mc.texture_rel_path(namespace, category, name)
    out_rel = f"{pack_root}/{rel}"

    warnings: list[str] = []
    if frames == 1 and (interpolate or frame_order or frametime != 1):
        warnings.append(
            "Animation settings were given but the sprite has one frame, so no sidecar was "
            "written — add frames to the sprite to animate it."
        )

    created = []
    if frames > 1:
        result = export.export_spritesheet(
            filename=filename, output=out_rel, sheet_type="vertical",
            padding=0, overwrite=overwrite,
        )
        png_path = result["output"]
        created.append(file_entry("image", png_path, "png"))
        sidecar = ensure_output_path(f"{out_rel}.mcmeta", overwrite=overwrite,
                                     error_type=ExportError)
        document = mc.animation_mcmeta(frametime, interpolate, frame_order)
        sidecar.write_text(json.dumps(document, indent=2) + "\n",
                           encoding="utf-8", newline="\n")
        created.append(file_entry("metadata", str(sidecar), "mcmeta"))
    else:
        result = export.export_png(filename=filename, output=out_rel, overwrite=overwrite)
        png_path = result["output"]
        created.append(file_entry("image", png_path, "png"))

    if not (Path(pack_root) / "pack.mcmeta").exists():
        warnings.append(
            f"No pack.mcmeta in '{pack_root}' — the game will not load the directory as a "
            "resource pack. Run write_pack_mcmeta(pack_root=...)."
        )

    actions = [f"Texture written to {rel} ({frames} frame(s))."]
    if frames > 1:
        seconds = frames * frametime * mc.MS_PER_TICK / 1000
        actions.append(
            f"Vertical strip {info['width']}x{info['height'] * frames} + sidecar at "
            f"{frametime} tick(s)/frame — a {seconds:g}s loop"
            + (", interpolated." if interpolate else ".")
        )
    if category in mc.TILING_CATEGORIES:
        actions.append(
            f"Check the wrap-around edges before shipping: "
            f"validate_minecraft_texture('{filename}', category='{category}', tiling=True)."
        )
    return workflow_manifest(
        "minecraft_texture",
        sprite=sprite_summary(info),
        created_files=created,
        warnings=warnings,
        suggested_next_actions=actions,
    )


# --------------------------------------------------------------------------- #
# Validation                                                                  #
# --------------------------------------------------------------------------- #
def _read_frame_pixels(filename: str, width: int, height: int, frame: int) -> list[list[str]]:
    """Read one frame's full pixel grid, in bands small enough for get_pixels' cap."""
    band = max(1, _PIXELS_PER_READ // max(1, width))
    rows: list[list[str]] = []
    y = 0
    while y < height:
        chunk = min(band, height - y)
        result = inspect.get_pixels(filename, x=0, y=y, width=width, height=chunk, frame=frame)
        rows.extend(result["pixels"])
        y += chunk
    return rows


@mcp.tool()
def validate_minecraft_texture(
    filename: str,
    category: str | None = None,
    texture_size: int | None = None,
    tiling: bool = False,
    expected_frames: int | None = None,
    max_palette_size: int | None = None,
    pack_root: str | None = None,
    namespace: str = "minecraft",
    texture_name: str | None = None,
    warn_ratio: float = 2.0,
    error_ratio: float = 4.0,
) -> dict:
    """Check a sprite against Minecraft's texture rules before it ships.

    Always checks that frames are square and power-of-two. Optionally checks the declared
    size, frame count and palette budget; if `tiling` is set, measures the wrap-around
    seams of every frame; if `pack_root` is given, confirms an animated texture has its
    ``.png.mcmeta`` sidecar.

    **The seam check** does not require the first and last columns to match — that is only
    true of a texture with no variation, and would reject most real block art. It compares
    the wrap transition against the texture's own interior column-to-column transitions and
    reports the ratio, so a borderline verdict can be judged rather than taken on faith.
    `warn_ratio` / `error_ratio` set where "suspect" and "seam" begin.

    Returns a ``workflow_manifest.v1`` manifest (kind ``validation``) whose `validation`
    block is ``{passed, checks, errors, warnings}``, plus per-frame seam measurements
    under `tiling` when the seam check ran.
    """
    info = inspect.get_sprite_info(filename)
    width, height, frames = info["width"], info["height"], info["frameCount"]

    frame_tilings: list[dict] | None = None
    tiling_note: str | None = None
    if tiling:
        if width < 3 or height < 3:
            tiling_note = (f"sprite is {width}x{height}; a seam check needs at least 3x3 to "
                           "have interior transitions to compare the wrap against")
        else:
            frame_tilings = [
                mc.evaluate_tiling(_read_frame_pixels(filename, width, height, f),
                                   warn_ratio=warn_ratio, error_ratio=error_ratio)
                for f in range(1, frames + 1)
            ]

    has_mcmeta: bool | None = None
    if pack_root is not None:
        if category is None:
            raise ExportError("pack_root was given without category; both are needed to "
                              "locate the exported texture.")
        name = texture_name or Path(filename).stem
        png = Path(pack_root) / mc.texture_rel_path(namespace, category, name)
        has_mcmeta = png.with_suffix(".png.mcmeta").exists()

    report = mc.evaluate_texture(
        info,
        category=category,
        texture_size=texture_size,
        tiling=tiling,
        frame_tilings=frame_tilings,
        max_palette_size=max_palette_size,
        expected_frames=expected_frames,
        has_mcmeta=has_mcmeta,
    )
    if tiling_note:
        report["warnings"].append(tiling_note)
        report["checks"].append({"name": "tiling.skipped", "ok": False, "level": "warning",
                                 "detail": tiling_note})

    actions = (
        [f"{filename} is a valid {width}x{width} Minecraft texture ({frames} frame(s))."]
        if report["passed"] else [f"Fix: {e}" for e in report["errors"]]
    )
    if frame_tilings and report["passed"]:
        worst = max(
            (r[axis]["ratio"] or 0.0) for r in frame_tilings for axis in ("horizontal", "vertical")
        )
        actions.append(f"Tiling edges are clean (worst wrap/interior ratio {worst:.2f}, "
                       f"flagged at {warn_ratio}).")

    manifest = workflow_manifest(
        "validation",
        sprite=sprite_summary(info),
        validation=report,
        warnings=report["warnings"],
        suggested_next_actions=actions,
    )
    if frame_tilings:
        manifest["tiling"] = {"frames": frame_tilings, "warn_ratio": warn_ratio,
                              "error_ratio": error_ratio}
    return manifest
